MVCSozluk/Controllers/MembersController.cs
using BLL;
using Entity;
using Entity.ViewModels;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace MVCSozluk.Controllers
{
    public class MembersController : Controller
    {
        UnitOfWork _uw = new UnitOfWork();
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult LogOff()
        {
            HttpContext.GetOwinContext().Authentication.SignOut();
            return RedirectToAction("Index", "Home");
        }

        public ActionResult Register()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Register(Person person, string Pass, HttpPostedFileBase img)
        {
            UserStore<Person> store = new UserStore<Person>(UnitOfWork.Create()); //managera ulaşabilmek için kullanılıyor dbsetleri ayarlayan kısım
            UserManager<Person> manager = new UserManager<Person>(store);//update, şifre oluşturma, şifreyi unutup baştan oluşturma, her şeyi yapabilir manager
            var result = manager.Create(person, Pass);
            if (result.Succeeded)
            {
                //resim varsa kişinin id si ile kaydet //anasayfaya ya da logine yönlendir//Uploads/Members/
                if (img != null)
                {
                    string path = Server.MapPath("/Uploads/Members/");
                    img.SaveAs(path + person.Id + ".jpg");

                    person.HasPhoto = true;
                    manager.Update(person);
                }

                return RedirectToAction("Index", "Home");
            }
            else
            {
                //View içine hataları gönder //hataları uygun bir html ile göster
                ViewBag.Errors = result.Errors;
            }

            return View();
        }

        public ActionResult _LoginModal()
        {
            return View();
        }

        public JsonResult Login(LoginViewModel info)
        {
            //1.Sign in Managera ulaş
            ApplicationSignInManager signInManager = HttpContext.GetOwinContext().Get<ApplicationSignInManager>();

            //2.Giriş yapmayı dene (result döner)
            SignInStatus result = signInManager.PasswordSignIn(info.Email, info.Password, true, false);

            //3.Sonucu döndür
            switch (result)
            {
                case SignInStatus.Success:
                    return Json(new { success = true });
                case SignInStatus.Failure:
                    return Json(new { success = false }); ;
            }
            return Json(new { success = false });
        }

        public ActionResult MyAccount()
        {
            string uid = User.Identity.GetUserId();
            Person person = _uw.db.Users.Find(uid);

            if (person.HasPhoto)
            {
                ViewBag.Photo = "/Uploads/Members/" + uid + ".jpg";
            }
            MyAccountViewModel vm = new MyAccountViewModel();
            vm.Email = person.Email;
            vm.PhoneNumber = person.PhoneNumber;
            return View(vm);
        }

        [HttpPost]
        public ActionResult MyAccount(MyAccountViewModel info, HttpPostedFileBase imgFile)
        {
            UserStore<Person> store = new UserStore<Person>(UnitOfWork.Create());
            UserManager<Person> manager = new UserManager<Person>(store);

            string uid = User.Identity.GetUserId();
            Person person = manager.FindById(uid);
            person.Email = info.Email;
            person.PhoneNumber = info.PhoneNumber;

            if (imgFile != null)
            {
                string path = Server.MapPath("/Uploads/Members/");
                string old = path + person.Id + ".jpg";
                if (System.IO.File.Exists(old))
                    System.IO.File.Delete(old);

                string _new = path + person.Id + ".jpg";
                imgFile.SaveAs(_new);

                person.HasPhoto = true;
            }

            manager.Update(person);
            if (person.HasPhoto)
            {
                ViewBag.Photo = "/Uploads/Members/" + uid + ".jpg";
            }
            return View(info);
        }

        public ActionResult ChangePass()
        {
            return View();
        }

        [HttpPost]
        public ActionResult ChangePass(string oldP, string newP)
        {
            UserStore<Person> store = new UserStore<Person>(_uw.db);
            UserManager<Person> manager = new UserManager<Person>(store);

            string uid = User.Identity.GetUserId();
            Person person = manager.FindById(uid);

            bool isCorrect = manager.CheckPassword(person, oldP);
            if (isCorrect)
            {
                IdentityResult r = manager.ChangePassword(uid, oldP, newP);
                if (r.Succeeded)
                    ViewBag.Success = true;
                else
                    ViewBag.Errors = r.Errors;
            }
            else
                ViewBag.WrongPassWord = false;
            return View();
        }
    }
}

MVCSozluk/Controllers/WordRequestController.cs
using BLL;
using Entity;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCSozluk.Controllers
{
    public class WordRequestController : Controller
    {
        UnitOfWork _uw = new UnitOfWork();
        public ActionResult Index(int? sil)
        {
            if (sil.HasValue)
            {
                _uw.WordRequests.Delete(sil.Value);
                _uw.Complete();
            }
            var list = _uw.WordRequests.GetAll();
            return View(list);
        }

        public ActionResult Create()
        {
            ViewBag.Langs = _uw.Languages.GetAll().Select(x => new SelectListItem
            {//<option> ları üretir
                Text = x.Name,
                Value = x.Id.ToString()
            });
            return View();
        }
        [HttpPost]
        public ActionResult Create(WordRequest r)
        {
            if (ModelState.IsValid)
            {
                string uid = User.Identity.GetUserId();
                var user = _uw.db.Users.Find(uid);
                r.Person = user;
                _uw.WordRequests.Add(r);
                _uw.Complete();
                return RedirectToAction("Index");
            }

            ViewBag.Langs = _uw.Languages.GetAll().Select(x => new SelectListItem
            {
                Text = x.Name,
                Value = x.Id.ToString()
            });
            return View(r);
        }
    }
}

MVCSozluk/Controllers/WordsController.cs
using BLL;
using Entity;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace MVCSozluk.Controllers
{
    [Authorize(Roles = "Admin")]
    public class WordsController : Controller
    {
        UnitOfWork _uw = new UnitOfWork();
        public ActionResult Index(int? langid, int? sil)
        {
            if (sil.HasValue)
            {
                _uw.Words.Delete(sil.Value);
                _uw.Complete();
                return RedirectToAction("Index", new { @langid = langid });
            }
            List<SelectListItem> langs = _uw.Languages.GetAll().Select(x => new SelectListItem()
            {
                Text = x.Name,
                Value = x.Id.ToString()
            }).ToList();

            langs.Insert(0, new SelectListItem()
            {
                Text = "Seçiniz",
                Value = ""
            });

            ViewData["LangOptions"] = langs;
            if (langid.HasValue)
            {
                ViewBag.langid = langid.Value;
                var list = _uw.Words.Search(x => x.Language_Id == langid.Value);
                return View(list);
            }
            else
                return View();
        }

        public ActionResult Create()
        {
            //ViewBag.LangOption = _uw.Languages.GetAll();
            //ViewData["LangOptions"] = _uw.Languages.GetAll();
            TempData["LangOptions"] = _uw.Languages.GetAll()
                .Select(x => new SelectListItem
                {
                    Text = x.Name,
                    Value = x.Id.ToString()
                });// TempData artı yönü controllerdan controllera bir seferlik aktarım yapıyor. Ordan başka bir sayfaya giderse veriyi saklamayacaktır.
            return View();
        }

        [HttpPost]
        public ActionResult Create(string WordTxt, int LanguageId)
        {
            if (string.IsNullOrEmpty(WordTxt))
                ModelState.AddModelError("", "Kelime boş bırakılamaz");

            if (ModelState.IsValid)
            {
                Word w = new Word();
                w.WordTxt = WordTxt;
                w.Language_Id = LanguageId;

                var langs = _uw.Languages.GetAll();

                w.Translations = new List<Word>();

                foreach (var item in langs)
                {
                    string input = Request.Form["ceviri" + item.Id];

                    string[] words = input.Split(',');

                    foreach (string item2 in words)
                    {
                        if (!string.IsNullOrEmpty(item2))
                        {
                            Word ceviri = new Word();
                            ceviri.Language_Id = item.Id;
                            ceviri.WordTxt = item2;
                            w.Translations.Add(ceviri);
                        }
                    }

                }

                _uw.Words.Add(w);
                _uw.Complete();
                return RedirectToAction("Index");
            }
            return View();
        }

        public JsonResult AutoComplete(int langid, string q)
        {
            var list = _uw.Words.Search(x => x.Language_Id == langid && x.WordTxt.ToLower().StartsWith(q.ToLower())).Select(x => x.WordTxt).ToList();
            return Json(list, JsonRequestBehavior.AllowGet);
        }
    }
}

MVCSozluk/Views/Shared/_Layout.cshtml
<!Doctype html>
<html>
<head>
    <title>Sözlük</title>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
    <!------ Include the above in your HEAD tag ---------->
    <link href="https://fonts.googleapis.com/css?family=Oleo+Script:400,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Teko:400,700" rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link href="~/Content/Site.css" rel="stylesheet" /> @*@Styles.Render("~/Content/css")*@

</head>
<body>
    <nav class="navbar navbar-default navbar-inverse" role="navigation">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @*<a class="navbar-brand" href="#">Login dropdown</a>*@
                @Html.ActionLink("Sözlük", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li class="active">
                        @Html.ActionLink("Hakkımızda", "About", "Home")
                    </li>
                    <li>
                        @Html.ActionLink("İletişim", "Contact", "Home")
                    </li>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li class="dropdown">
                            <a href="void(0)" class="dropdown-toggle" data-toggle="dropdown">Bana Özel <span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li>
                                    @Html.ActionLink("Hesabım", "MyAccount", "Members")
                                </li>
                                <li>
                                    @Html.ActionLink("Şifremi Değiştir", "ChangePass", "Members")
                                </li>
                                <li class="divider"></li>
                                <li>
                                    @Html.ActionLink("Kelime İstekleri", "Index", "WordRequest")
                                </li>
                                @if (User.IsInRole("Admin"))
                                {
                                    <li class="divider"></li>
                                    <li>@Html.ActionLink("Kelimeler", "Index", "Words")</li>
                                    <li>@Html.ActionLink("Yeni Kelime Ekle", "Create", "Words")</li>
                                }

                            </ul>
                        </li>
                    }
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li>
                            <p class="navbar-text">Merhaba @User.Identity.Name </p>
                        </li>
                        <li>
                            @Html.ActionLink("Çıkış Yap", "LogOff", "Members")
                        </li>
                    }
                    else
                    {
                        <li><p class="navbar-text">Already have an account?</p></li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><b>Login</b> <span class="caret"></span></a>
                            <ul id="login-dp" class="dropdown-menu">
                                <li>
                                    <div class="row">
                                        <div class="col-md-12">
                                            Login via
                                            <div class="social-buttons">
                                                <a href="#" class="btn btn-fb"><i class="fa fa-facebook"></i> Facebook</a>
                                                <a href="#" class="btn btn-tw"><i class="fa fa-twitter"></i> Twitter</a>
                                            </div>
                                            or
                                            @Html.Action("_LoginModal", "Members")
                                        </div>
                                        <div class="bottom text-center">
                                            New here ? @*<a href="#"><b>Join Us</b></a>*@
                                            @Html.ActionLink("Kayıt Ol", "Register", "Members", null, new { @class = "bold" })
                                        </div>
                                    </div>
                                </li>
                            </ul>
                        </li>
                    }
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>
    @RenderBody()
    @RenderSection("Scripts", false)
</body>
</html>